# Generated by Django 3.1.7 on 2021-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
